### ISSUE TITLE
Incorrect SVC save/load methods implementation

### ISSUE THREAD

**Issue by epoxa** [andrewdalpino/Rubix-engine#275] opened 2023-02-10 19:13 UTC
Internal field `classes` of class SVC set up during `train` method call only. So if we try to load model into newly created classifier and try to make prediction we get an exception `TypeError: Return value of Rubix\ML\Classifiers\SVC::predictSample() must be of the type string, null returned`

Steps to reproduce:

```
<?php

require_once "vendor/autoload.php";

$filename = tempnam(sys_get_temp_dir(),'svm');

$svm = new \Rubix\ML\Classifiers\SVC();
$data = new \Rubix\ML\Datasets\Labeled([[1],[2]],['one','two']);
$svm->train($data);

$svm->save($filename);

$svm = new \Rubix\ML\Classifiers\SVC();
$svm->load($filename);
$data = new \Rubix\ML\Datasets\Unlabeled([[1]]);
$svm->predict($data); // Got the exception
```

**Comment by andrewdalpino** [comment] 2023-02-21 19:27
Hey @epoxa thanks for the bug report, will take a look ASAP

**Comment by andrewdalpino** [comment] 2023-03-12 22:04
Ok I see the issue, it looks like it's the correct implementation of the SVM extension API. The problem is due to a limitation of the SVM extension. Since the authors of the SVM extension decided to roll their own saving and loading mechanism, there is no way to store the class ordinal to label mapping.

It's also worth noting here that the authors of the SVM extension have been MIA for more than a few years now. If we continue to see that users are using the SVM functionality in their projects, it may be worth forking the SVM extension and fixing all the issues with it.

I guess we'll close this since it's not a bug, but will probably want to make a note of the limitation of the underlying SVM extension in the docs.

**Closed as completed by andrewdalpino** 2023-03-12 22:04 UTC
